version: "3.9"

services:
  library:
    container_name: main
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
        - .:/app
        - /app/node_modules
    ports:
        - "${PORT}:${PORT}"
        - "9229:9229"
    command: npm run start:prod