version: "3.9"

services:
  main:
    container_name: main
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .env.production
    volumes:
        - .:/app
        - /app/node_modules
    ports:
        - 3000:3000
        - "9229:9229"
    command: npm run start:prod